remote_theme: "mmistakes/so-simple-theme@3.2.0"
url: https://vipera.dev
baseurl: #
title: "Vipera"
logo: /assets/vipera-v3-avatar.png
description: A framework for dynamic languages on micro-core architectures
og:site_name: #
google_fonts: 
  - name: "Play"
    weights: "400,400i,700,700i"
    
